language: c
env:
 global:
  - PRE_INSTALL_HOOK="sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
  - POST_INSTALL_HOOK="sh ./.yaks-ci.sh"
  - OCAML_VERSION=4.07.0 OPAM_VERSION=2.0.0