language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .yaks-ci.sh
env:
    global:
    - DEPOPTS="lwt dune logs fmt cmdliner cmdliner ppx_deriving uuidm yojson lwt_ppx lwt_log ppx_cstruct atdgen cohttp-lwt-unix"
    - PINS="yaks-core:. yaks-be-mm:.yaks-fe-rest:. cohttp-lwt-unix:--dev cohttp:--dev"
    - PACKAGE=yaks 
    matrix:
    - OCAML_VERSION=4.07 
