language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .yaks-ci.sh
env:
    - OCAML_VERSION=4.07 DEPOPTS=lwt dune logs fmt cmdliner cmdliner ppx_deriving uuidm yojson lwt_ppx lwt_log ppx_cstruct atdgen cohttp-lwt-unix PACKAGE=yaks-core PACKAGE=yaks-fe-rest PACKAGE=yaks-be-mm PACKAGE=yaks 