language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .yaks-ci.sh
env:
    - OCAML_VERSION=4.07.0 OPAM_VERSION=2.0.0