language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .yaks-ci.sh
env:
    global:
    - DEPOPTS="lwt dune logs fmt cmdliner cmdliner ppx_deriving uuidm yojson lwt_ppx lwt_log ppx_cstruct atdgen cohttp-lwt-unix cohttp cohttp-mirage" 
    - PINS="cohttp-mirage:--dev cohttp-lwt-unix:--dev cohttp:--dev apero-core:https://github.com/atolab/apero.git apero-net:https://github.com/atolab/apero.git apero:https://github.com/atolab/apero.git yaks-core:./src/yaks/yaks-core yaks-be-mm:./src/yaks/yaks-be/yake-be-mm yaks-fe-rest:./src/yaks/yaks-fe/yake-fe-rest yaks-fe-rest-mirage:./src/yaks/yaks-fe/yake-fe-rest-mirage yaks:."
    - PACKAGE=yaks 
    matrix:
    - OCAML_VERSION=4.07 
