== Operations on User Space

The User Space can be addressed via URLs with any path not starting with `*/@*`

=== Put
[options="header",cols="20,80"]
|=======================================================================================
| Operation         | *put(path, value)*
| Description a| 
    - Causes the notification of all _subscriptions_ whose selector matches the givent *path* (in URL), and

    - Stores the tuple _{<path,value>}_ on all _storages_ in YAKS whose _selector_ matches *path*
| URL               | `*/path*`
| Method            | *PUT*
| Headers           | _None_
| Body              | the value (Json format)
| Success Responses a| 
    - *204 (No Content)*: if put succeed
| Error Responses a|
    - *400 (Bad Request)*: if the path is malformed.
|=======================================================================================

=== Update
[options="header",cols="20,80"]
|=======================================================================================
| Operation         | *update(path, deltaValue)*
| Description | 
    Allows to *put* a delta, thus avoiding to distribute the entire value.
| URL               | `*/selector*`
| Method            | *PATCH*
| Headers           | _None_
| Body              | the delta value (Json format)
| Success Responses a| 
    - *204 (No Content)*: if update succeed
| Error Responses a|
    - *400 (Bad Request)*: if the path is malformed.
|=======================================================================================

=== Remove
[options="header",cols="20,80"]
|=======================================================================================
| Operation         | *remove(path)*
| Description | 
    Removes from all  Yaks's storages the tuple having the given *path* (in URL).
| URL               | `*/path*`
| Method            | *DELETE*
| Headers           | _None_
| Body              | _None_
| Success Responses a| 
    - *204 (No Content)*: in any case.
| Error Responses a|
    - *400 (Bad Request)*: if the path is malformed.
|=======================================================================================

=== Get
[options="header",cols="20,80"]
|=======================================================================================
| Operation         | *get(selector)*
| Description | 
    Gets the set of tuples _{<path,value>}_ available in YAKS for which _path_
    matches the given *selector* (in URL).
| URL               | `*/selector*`
| Method            | *GET*
| Headers           | _None_
| Body              | _None_
| Success Responses a| 
    - *200 (Ok)*:
      * with body: a list of Key/Value (Json format). +
        _Notice that is no matching key is found, the body will be empty._
| Error Responses a|
    - *400 (Bad Request)*: if the selector is malformed.
|=======================================================================================

=== Eval
[options="header",cols="20,80"]
|=======================================================================================
| Operation         | *eval(selector)*
| Description | 
    Requests the evaluation of registered evals whose registration 
    _path_ matches the given *selector* (in URL).
| URL               | `*/selector*`
| Method            | *GET*
| Headers           | *"is.yaks.eval"*
| Body              | _None_
| Success Responses a| 
    - *200 (Ok)*:
      * with body: a list of Key/Value (Json format). +
        _Notice that is no matching key is found, the body will be empty._
| Error Responses a|
    - *400 (Bad Request)*: if the selector is malformed.
|=======================================================================================




== Operations on Admin Space

The Admin Space can be addressed with the same `PUT`, `GET` and `DELETE` HTTP requests than
the User Space, but via URLs with paths starting with `*/@*`.

The following paths can be used to administrate a Yaks service:

[options="header",cols="10,90"]
|=======================================================================================
| Path                                | Authorized HTTP methods
| `/@/<yaks>`                                      a|
    - *GET*: returns informations on the Yaks service with identifier *_<yaks>_*. +
      Notice that *_<yaks>_* can be `local`, meaning the request addresses the Yaks service
      receiving this HTTP request. This is true for all paths below.
| `/@/<yaks>/transport/zenoh`                      a|
    - *GET*: returns configuration properties of the Zenoh transport configuration.
| `/@/<yaks>/frontend/<feid>`                      a|
    - *GET*: returns configuration properties of the frontend with identifier *_<feid>_*.
    - *PUT*: add a frontend with identifier *_<feid>_* and configured with the properties
      passed in the request body.
    - *DELETE*: removed the frontend with identifier *_<feid>_*.
| `/@/<yaks>/frontend/<feid>/session/<sid>`        a|
    - *GET*: returns properties of the session with identifier *_<sid>_*.
    - *DELETE*: force close the session with identifier *_<sid>_*.
| `/@/<yaks>/frontend/<feid>/session/<sid>/ subscription/<subid>`        a|
    - *GET*: returns the selector used by the subscription with identifier *_<subid>_*.
| `/@/<yaks>/backend/<beid>`                       a|
    - *GET*: returns configuration properties of the backend with identifier *_<beid>_*.
    - *PUT*: add a backend with identifier *_<beid>_* and configured with the properties
      passed in the request body.
    - *DELETE*: removed the backend with identifier *_<beid>_*.
| `/@/<yaks>/backend/<beid>/storage/<stid>`        a|
    - *GET*: returns configuration properties of the storage with identifier *_<stid>_*.
    - *PUT*: add a storage with identifier *_<stid>_* using the backend with identifier 
             *_<beid>_* and configured with the properties passed in the request body.
    - *DELETE*: removed the storage with identifier *_<stid>_*.
| `/@/<yaks>/backend/auto/storage/<stid>`          a|
    - *PUT*: add a storage with identifier *_<stid>_* using an automatically selected
             backend and configured with the properties passed in the request body. +
             The selected backend will be the one with the most compatible properties
             wrt. the storage's properties. 
|=======================================================================================

[NOTE]
====
Note that `GET` requests with selectors can be addressed to the Admin Space to browse it.
E.g.:
====

[options="header",cols="10,90"]
|=======================================================================================
| Path used for `GET`              | Result
| `/@/<yaks>/**`                   |
    All transports, frontends, backends, sessions and storages hosted by the Yaks service
    with their associated properties.
| `/@/<yaks>/frontend/*`                   |
    All the frontends hosted by the Yaks service with their associated properties.
| `/@/<yaks>/backend/*`                    |
    All the backends hosted by the Yaks service with their associated properties.
| `/@/<yaks>/frontend/<feid>/session/*`    |
    All the sessions connected to the frontend *_<feid>_* of the Yaks service with
    their associated properties.
| `/@/<yaks>/frontend/\*/session/*`        |
    All the sessions connected to the Yaks service with their associated properties.
| `/@/<yaks>/backend/<beid>/storage/*`    |
    All the storages hosted by the backend *_<beid>_* of the Yaks service with
    their associated properties.
| `/@/<yaks>/backend/\*/storage/*`        |
    All the storages hosted by the Yaks service with their associated properties.
|=======================================================================================

